server:
  port: 80
  servlet:
    context-path: /api/vx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.193.94:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    flag:
  #    hikari:
  #      maximum-pool-size: 50
  #      minimum-idle: 10

  application:
    name: "xiaopeng_server"
## mybatis
##实现mapper接口配置见mapper和接口的绑定路径
##将带有下划线的表字段映射为驼峰格式的实体类属性
#mybatis:
#  mapper-locations: classpath*:/mybatis/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
wechatConfig:
  appId: 1
  appSecret: 1
